### ISSUE TITLE
MPI Distribution

### ISSUE THREAD

**Issue by dumitraand** [dumitraand/conwayapp#3]
**TODOs**:
- [ ] Add MPI lib
- [ ] Design spliting params && architecture
- [ ] Set master and joining logic
- [ ] Output to file
- [ ] Commit more than Cristian Dragu

**Comment by dumitraand** [comment]
### MPI Distribution
**Matrix Dimension**:
